receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 5s
    send_batch_size: 512

exporters:
  prometheus:
    endpoint: 0.0.0.0:8889

  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true

  loki:
    endpoint: http://loki:3100/loki/api/v1/push

  otlphttp/infrasage:
    endpoint: https://api.infrasage.dev
    encoding: json
    compression: none
    headers:
      X-API-Key: ${env:INFRASAGE_API_KEY}

  debug:
    verbosity: basic

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/jaeger, otlphttp/infrasage]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus, otlphttp/infrasage]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [loki, otlphttp/infrasage]
